# Generated by Django 4.1.7 on 2023-02-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=20)),
                ('password', models.TextField(max_length=20)),
                ('sex', models.CharField(choices=[('1', '男性'), ('2', '女性'), ('3', '秘密')], max_length=5)),
                ('img_name', models.ImageField(upload_to='')),
                ('game_lank', models.CharField(choices=[('1', 'ルーキー'), ('2', 'ブロンズ'), ('3', 'シルバー'), ('4', 'ゴールド'), ('5', 'プラチナ'), ('6', 'ダイアモンド'), ('7', 'マスター'), ('8', 'プレデター')], max_length=10)),
                ('like_weapons', models.CharField(max_length=50)),
                ('how_to_play', models.CharField(choices=[('1', 'ランクマッチがやりたい'), ('2', 'カジュアルマッチがやりたい'), ('3', 'ランクを上げたい'), ('4', 'カジュアルに遊びたい'), ('5', 'フレンドになりたい'), ('6', '今回限り'), ('7', '長く遊べるフレンド募集')], max_length=20)),
                ('play_timezone', models.CharField(max_length=50)),
                ('self_intro', models.TextField()),
                ('ps_id', models.CharField(max_length=30)),
            ],
        ),
    ]
