# Generated by Django 4.1.7 on 2023-02-23 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='game_lank',
        ),
        migrations.RemoveField(
            model_name='user',
            name='how_to_play',
        ),
        migrations.RemoveField(
            model_name='user',
            name='img_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='like_weapons',
        ),
        migrations.RemoveField(
            model_name='user',
            name='play_timezone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ps_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='self_intro',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
        migrations.AddField(
            model_name='user',
            name='mail',
            field=models.EmailField(default='aaa@sample.jp', max_length=254),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(blank=True, choices=[('1', '男性'), ('2', '女性'), ('3', '秘密')], max_length=5, null=True)),
                ('img_name', models.ImageField(blank=True, null=True, upload_to='')),
                ('game_lank', models.CharField(blank=True, choices=[('1', 'ルーキー'), ('2', 'ブロンズ'), ('3', 'シルバー'), ('4', 'ゴールド'), ('5', 'プラチナ'), ('6', 'ダイアモンド'), ('7', 'マスター'), ('8', 'プレデター')], max_length=10, null=True)),
                ('like_weapons', models.CharField(blank=True, max_length=50, null=True)),
                ('how_to_play', models.CharField(blank=True, choices=[('1', 'ランクマッチがやりたい'), ('2', 'カジュアルマッチがやりたい'), ('3', 'ランクを上げたい'), ('4', 'カジュアルに遊びたい'), ('5', 'フレンドになりたい'), ('6', '今回限り'), ('7', '長く遊べるフレンド募集')], max_length=20, null=True)),
                ('play_timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('self_intro', models.TextField(blank=True, null=True)),
                ('ps_id', models.CharField(blank=True, max_length=30, null=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loginapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_station', models.BooleanField(default=False)),
                ('x_box', models.BooleanField(default=False)),
                ('switch', models.BooleanField(default=False)),
                ('pc', models.BooleanField(default=False)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loginapp.user')),
            ],
        ),
    ]
